spring:
  aop:
    proxyTargetClass: true
  application:
    name: common-service-apigateway
  boot:
    admin:
      api-path: http://admin.orrin.com:7999
  redis:
    host: localhost
    port: 6379
    database: 5
  datasource:
    druid:
      url: jdbc:log4jdbc:mysql://localhost:3306/spring-cloud-apigateway?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: net.sf.log4jdbc.DriverSpy
      filter:
        config:
          enabled: true
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
  jpa:
    show-sql: true
    properties:
      jadira.usertype.autoRegisterUserTypes: true

# Define the port where the API gateway server would be running
server:
  port: 8080

# Define the Eureka server that handles service registration
eureka:
  instance:
      hostname: api.orrin.com
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://eureka.orrin.com:${eureka.instance.port}/eureka/

zuul:
  routes:
    business-service-oauth-resource:
      path: /business/oauthresource/**
      serviceId: business-service-oauth-resource
    business-service-product:
      path: /business/product/**
      serviceId: business-service-product
    business-service-product-withoutsso:
      path: /business/productwithoutsso/**
      serviceId: business-service-product-withoutsso
    common-service-uaa:
      #sensitiveHeaders:
      path: /common/uaa/**
      #stripPrefix: false
      serviceId: common-service-uaa
  add-proxy-headers: true
  sensitive-headers: Cookie,Set-Cookie
info:
  version: @project.version@