spring:
  boot:
    admin:
      url: http://admin.orrin.com:7999
      username: admin       #These two are needed so that the client
      password: pass   #can register at the protected server api
      client:
        metadata:
          user.name: admin         #These two are needed so that the server
          user.password: pass  #can access the proteceted client endpoints
  redis:
    host: localhost
    port: 6379
    database: 5
  datasource:
    druid:
      url: jdbc:log4jdbc:mysql://localhost:3306/spring-cloud-apigateway?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: net.sf.log4jdbc.DriverSpy
      filter:
        config:
          enabled: true
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000