spring:
  aop:
    proxyTargetClass: true
  application:
    name: common-service-apigateway
  boot:
    admin:
      api-path: http://admin.orrin.com:7999

# Define the port where the API gateway server would be running
server:
  port: 8080

# Define the Eureka server that handles service registration
eureka:
  instance:
      hostname: api.orrin.com
      port: 8761
  client:
    serviceUrl:
      defaultZone: http://eureka.orrin.com:${eureka.instance.port}/eureka/

zuul:
  routes:
    business-service-product:
      path: /business/product/**
      serviceId: business-service-product
    business-service-product-withoutsso:
      path: /business/productwithoutsso/**
      serviceId: business-service-product-withoutsso
    common-service-uaa:
      #sensitiveHeaders:
      path: /common/uaa/**
      #stripPrefix: false
      serviceId: common-service-uaa
  add-proxy-headers: true
info:
  version: @project.version@

apigateway:
  jwt:
    keyValue:   |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
        -----END PUBLIC KEY-----