spring:
  application:
    name: common-service-zipkin

# Define the port where the Service Registry server would be running
server:
  port: 8763

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    port: ${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.orrin.com}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
