spring:
  application:
    name: common-service-zipkin

management:
  security:
    enabled: false

# Define the port where the Service Registry server would be running
server:
  port: 8763

# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    port: 8761
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://eureka.orrin.com:8761}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
