spring:
  application:
    name: common-service-admin
  cloud:
    config:
      enabled: false
  boot:
    admin:
      username: "${security.user.name}"       #These two are needed so that the client
      password: "${security.user.password}"   #can register at the protected server api

security:
  user:
    name: admin
    password: pass

server:
  port: 7999

# tag::configuration-eureka[]
eureka:  #<1>
  instance:
    leaseRenewalIntervalInSeconds: 10
    hostname: admin.orrin.com
    metadata-map:
      user.name: "${security.user.name}"         #These two are needed so that the server
      user.password: "${security.user.password}"  #can access the proteceted client endpoints
      management.context-path: /mgmt
      health.path: /mgmt/health
    health-check-url-path: /mgmt/health

  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://eureka.orrin.com:8761}/eureka

#  security:
#    enabled: false  #<2>
# end::configuration-eureka[]

# tag::configuration-ui-hystrix[]
spring.boot.admin.routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
# end::configuration-ui-hystrix[]

# tag::configuration-ui-turbine[]
spring.boot.admin.turbine:
  clusters: default
  location: turbine  #<1>
# end::configuration-ui-turbine[]

logging:
  level:
    root: DEBUG
    java.sql: DEBUG
    com.orrin.: debug


info:
  version: @project.version@
management:
  context-path: /mgmt
