sys_env: dev
spring:
  boot:
    admin:
      api-path: http://admin.orrin.com:7999
  redis:
    host: localhost
    port: 6379
    database: 5

  datasource:
    druid:
      url: jdbc:log4jdbc:mysql://localhost:3306/spring-cloud-uaa?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
      username: root
      password: 123456
      driver-class-name: net.sf.log4jdbc.DriverSpy
      filter:
        config:
          enabled: true
        stat:
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000

management:
  security:
    enabled: false

logging:
  level:
    root: DEBUG
    java.sql: DEBUG
    com.orrin.: debug
